// frontend/src/components/admin/tabs/CandidatesTab.jsx
import { Lock, Unlock } from 'lucide-react';
import { useState } from 'react';

export default function CandidatesTab({ candidates, isLocked = false }) {
  const [editingId, setEditingId] = useState(null);
  const [editData, setEditData] = useState({});

  const handleEdit = (candidate) => {
    setEditingId(candidate.id);
    setEditData({ ...candidate });
  };

  const handleCancel = () => {
    setEditingId(null);
    setEditData({});
  };

  const handleSave = async (candidateId) => {
    // TODO: Add API call to save candidate changes
    console.log('Saving candidate:', editData);
    setEditingId(null);
  };

  return (
    <div className="relative">
      {/* Lock Overlay */}
      {isLocked && (
        <div className="absolute inset-0 bg-black/40 backdrop-blur-sm flex items-center justify-center z-40 rounded-lg">
          <div className="bg-white rounded-lg p-6 shadow-xl text-center">
            <Lock size={32} className="text-slate-600 mx-auto mb-3" />
            <p className="text-sm font-semibold text-slate-900">Editing Locked</p>
            <p className="text-xs text-slate-600 mt-1">Unlock from the sidebar to edit candidates</p>
          </div>
        </div>
      )}

      <table className="w-full min-w-max border-collapse">
        <thead>
          <tr className="bg-white border-b border-gray-300">
            <th className="px-4 py-2.5 text-center text-xs font-medium text-gray-900 border-r border-gray-300 w-12">
              #
            </th>
            <th className="px-4 py-2.5 text-center text-xs font-medium text-gray-900 border-r border-gray-300 min-w-[100px]">
              Number
            </th>
            <th className="px-4 py-2.5 text-left text-xs font-medium text-gray-900 border-r border-gray-300 min-w-[200px]">
              Name
            </th>
            <th className="px-4 py-2.5 text-center text-xs font-medium text-gray-900 border-r border-gray-300 min-w-[100px]">
              Gender
            </th>
            {!isLocked && (
              <th className="px-4 py-2.5 text-center text-xs font-medium text-gray-900 min-w-[80px]">
                Actions
              </th>
            )}
          </tr>
        </thead>
        <tbody>
          {candidates && candidates.length > 0 ? (
            candidates.map((candidate, index) => (
              <tr key={candidate.id} className="border-b border-gray-200 hover:bg-gray-50">
                <td className="px-4 py-2.5 text-center text-sm text-gray-700 border-r border-gray-200">
                  {index + 1}.
                </td>
                <td className="px-4 py-2.5 text-center text-sm text-gray-900 border-r border-gray-200">
                  {editingId === candidate.id ? (
                    <input
                      type="text"
                      value={editData.number}
                      onChange={(e) => setEditData({ ...editData, number: e.target.value })}
                      className="w-full px-2 py-1 border border-slate-300 rounded text-sm"
                      disabled={isLocked}
                    />
                  ) : (
                    <strong>{candidate.number}</strong>
                  )}
                </td>
                <td className="px-4 py-2.5 text-left text-sm text-gray-900 border-r border-gray-200">
                  {editingId === candidate.id ? (
                    <input
                      type="text"
                      value={editData.name}
                      onChange={(e) => setEditData({ ...editData, name: e.target.value })}
                      className="w-full px-2 py-1 border border-slate-300 rounded text-sm"
                      disabled={isLocked}
                    />
                  ) : (
                    candidate.name
                  )}
                </td>
                <td className="px-4 py-2.5 text-center text-sm text-gray-700 border-r border-gray-200">
                  <span className={`inline-block px-2 py-0.5 rounded text-xs font-medium ${
                    candidate.gender === 'Female' ? 'bg-pink-100 text-pink-800' : 'bg-blue-100 text-blue-800'
                  }`}>
                    {candidate.gender}
                  </span>
                </td>
                {!isLocked && (
                  <td className="px-4 py-2.5 text-center text-sm">
                    {editingId === candidate.id ? (
                      <div className="flex gap-2 justify-center">
                        <button
                          onClick={() => handleSave(candidate.id)}
                          className="px-2 py-1 bg-green-500 hover:bg-green-600 text-white text-xs rounded font-semibold transition-colors"
                        >
                          Save
                        </button>
                        <button
                          onClick={handleCancel}
                          className="px-2 py-1 bg-slate-400 hover:bg-slate-500 text-white text-xs rounded font-semibold transition-colors"
                        >
                          Cancel
                        </button>
                      </div>
                    ) : (
                      <button
                        onClick={() => handleEdit(candidate)}
                        className="px-2 py-1 bg-blue-500 hover:bg-blue-600 text-white text-xs rounded font-semibold transition-colors"
                      >
                        Edit
                      </button>
                    )}
                  </td>
                )}
              </tr>
            ))
          ) : (
            <tr>
              <td colSpan={isLocked ? "4" : "5"} className="px-4 py-8 text-center text-sm text-gray-500">
                No candidates found
              </td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  );
}

// backend/resources/js/components/admin/tabs/CandidatesTab.vue
<template>
  <div>
    <div class="flex items-center justify-between mb-6">
      <h2 class="text-lg font-semibold text-gray-900">Candidates</h2>
      <button
        @click="showAddModal = true"
        class="px-4 py-2 bg-indigo-600 text-white text-sm font-medium rounded-lg hover:bg-indigo-700 transition-colors"
      >
        Add Candidate
      </button>
    </div>

    <!-- Candidates Table -->
    <div class="bg-white rounded-lg border border-gray-200 overflow-hidden">
      <table class="w-full">
        <thead class="bg-gray-50 border-b border-gray-200">
          <tr>
            <th class="py-3 px-4 text-left text-xs font-semibold text-gray-600 uppercase">#</th>
            <th class="py-3 px-4 text-left text-xs font-semibold text-gray-600 uppercase">Name</th>
            <th class="py-3 px-4 text-left text-xs font-semibold text-gray-600 uppercase">Gender</th>
            <th class="py-3 px-4 text-left text-xs font-semibold text-gray-600 uppercase">Team/Dept</th>
            <th class="py-3 px-4 text-center text-xs font-semibold text-gray-600 uppercase">Actions</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-100">
          <tr v-for="candidate in candidates" :key="candidate.id" class="hover:bg-gray-50">
            <td class="py-3 px-4 text-sm text-gray-900">{{ candidate.number }}</td>
            <td class="py-3 px-4 text-sm font-medium text-gray-900">{{ candidate.name }}</td>
            <td class="py-3 px-4 text-sm text-gray-600">{{ candidate.gender }}</td>
            <td class="py-3 px-4 text-sm text-gray-600">{{ candidate.team || candidate.department || '-' }}</td>
            <td class="py-3 px-4 text-center">
              <button @click="editCandidate(candidate)" class="text-indigo-600 hover:text-indigo-800 text-sm mr-2">Edit</button>
              <button @click="deleteCandidate(candidate.id)" class="text-red-600 hover:text-red-800 text-sm">Delete</button>
            </td>
          </tr>
          <tr v-if="!candidates?.length">
            <td colspan="5" class="py-8 text-center text-gray-500">No candidates yet</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { showError, showSuccess, showConfirm } from '../../../utils/alerts';

const props = defineProps({
  eventId: [String, Number],
  candidates: Array
});

const emit = defineEmits(['refresh']);

const showAddModal = ref(false);

const editCandidate = (candidate) => {
  // TODO: Implement edit modal
  console.log('Edit candidate:', candidate);
};

const deleteCandidate = async (id) => {
  const confirmed = await showConfirm('Delete Candidate', 'Are you sure you want to delete this candidate?', {
    confirmText: 'Delete',
    confirmColor: '#dc2626'
  });
  if (!confirmed) return;
  
  try {
    await fetch(`/api/candidates/${id}`, { method: 'DELETE' });
    emit('refresh');
    showSuccess('Candidate deleted successfully');
  } catch (error) {
    showError('Failed to delete candidate');
  }
};
</script>
