// frontend/src/components/admin/tabs/JudgesScoringTab.jsx
import { useState, useEffect, useRef, useCallback, useMemo } from 'react';
import { initializeEcho } from '../../../config/echo';
import { getApiBase, getCurrentEventId } from '../../../config/api';
import { useVotingWebSocket } from '../../../hooks/useVotingWebSocket';
import { loadColors, getGroupColor, getColumnColor } from 'nachtify';
import LiveIndicator from '../scoring/LiveIndicator';
import RoundHeader from '../scoring/RoundHeader';
import ScoreTable from '../scoring/ScoreTable';
import EmptyState from '../scoring/EmptyState';
import TableSkeleton from '../scoring/TableSkeleton';
import AdminPreloader from '../AdminPreloader';

export default function JudgesScoringTab({
  candidates,
  continuingEvent,
  // Control Props
  isVotingActive,
  eventSequence,
  currentSequenceIndex,
  onStartStop,
  onNext,
  onOpenEventDetails
}) {
  const [selectedCategory, setSelectedCategory] = useState(1);
  const [scores, setScores] = useState({});
  const [partnerScores, setPartnerScores] = useState({});
  const [judges, setJudges] = useState([]);
  const [categories, setCategories] = useState([]);
  const [activeRound, setActiveRound] = useState(null);
  const [fetchedCandidates, setFetchedCandidates] = useState([]);
  const [loading, setLoading] = useState(false);
  const [isLive, setIsLive] = useState(false);
  const [scoresHidden, setScoresHidden] = useState(false);
  const [candidateColors, setCandidateColors] = useState(() => loadColors());
  const pollingIntervalRef = useRef(null);
  const hasInitialized = useRef(false);

  // Check if we have duo participants
  const hasDuoParticipants = (fetchedCandidates || []).some(c => c.participant_type === 'duo' && c.partnership?.partner_name);

  // Use fetched candidates if available, otherwise fall back to prop
  const activeCandidates = fetchedCandidates.length > 0 ? fetchedCandidates : (candidates || []);

  // Fetch real data from backend - optimized with parallel requests
  useEffect(() => {
    // Skip if already initialized
    if (hasInitialized.current) {
      return;
    }

    const fetchData = async () => {
      try {
        const apiBase = getApiBase();

        // Use continuingEvent prop first, then fallback to localStorage
        let event = continuingEvent;

        if (!event) {
          const eventFromStorage = localStorage.getItem('continuingEvent');
          event = eventFromStorage ? JSON.parse(eventFromStorage) : null;
        }

        // If no event in localStorage, get from voting state
        if (!event) {
          const votingStateResponse = await fetch(`${apiBase}/api/voting/state`);
          const votingState = await votingStateResponse.json();

          if (votingState.event_id) {
            const eventResponse = await fetch(`${apiBase}/api/events/${votingState.event_id}`);
            event = await eventResponse.json();
          } else {
            setLoading(false);
            return;
          }
        }

        const eventId = event.id;

        // Fetch all critical data in parallel (optimized)
        const [votingStateResponse, roundsResponse, candidatesResponse, criteriaResponse, judgesResponse] = await Promise.all([
          fetch(`${apiBase}/api/voting/state?event_id=${eventId}`),
          fetch(`${apiBase}/api/rounds?event_id=${eventId}`),
          fetch(`${apiBase}/api/candidates?event_id=${eventId}`),
          fetch(`${apiBase}/api/criteria?event_id=${eventId}`),
          fetch(`${apiBase}/api/judges?event_id=${eventId}`)
        ]);

        // Check all responses
        if (!votingStateResponse.ok || !roundsResponse.ok || !candidatesResponse.ok || !criteriaResponse.ok) {
          throw new Error('Failed to fetch required data');
        }

        const votingState = await votingStateResponse.json();
        const rounds = await roundsResponse.json();
        const candidatesData = await candidatesResponse.json();
        const criteria = await criteriaResponse.json();

        setFetchedCandidates(candidatesData);
        setCategories(criteria);

        if (criteria.length > 0 && !selectedCategory) {
          setSelectedCategory(criteria[0].id);
        }

        // Get active round from voting state
        const currentRoundId = votingState.active_round_id;
        const currentRound = rounds.find(r => r.id === currentRoundId);
        setActiveRound(currentRound);

        // Process judges data
        let judgeList = [];
        if (judgesResponse.ok) {
          const judgesData = await judgesResponse.json();
          judgeList = judgesData.map(judge => ({
            id: judge.id,
            name: judge.name
          }));
        } else {
          // Fallback: create default judges if API fails
          judgeList = Array.from({ length: 5 }, (_, i) => ({
            id: i + 1,
            name: `Judge ${i + 1}`
          }));
        }
        setJudges(judgeList);

        // Initialize empty scores with criteria structure
        const emptyScores = {};
        judgeList.forEach(judge => {
          emptyScores[judge.id] = {};
          candidatesData.forEach(candidate => {
            emptyScores[judge.id][candidate.id] = {};
            criteria.forEach(criterion => {
              emptyScores[judge.id][candidate.id][criterion.id] = null;
            });
          });
        });
        setScores(emptyScores);

        // Check for duo participants in fetched data
        const hasDuo = candidatesData.some(c => c.participant_type === 'duo' && c.partnership?.partner_name);
        if (hasDuo) {
          const emptyPartnerScores = {};
          judgeList.forEach(judge => {
            emptyPartnerScores[judge.id] = {};
            candidatesData.forEach(candidate => {
              if (candidate.participant_type === 'duo' && candidate.partnership?.partner_name) {
                emptyPartnerScores[judge.id][candidate.id] = {};
                criteria.forEach(criterion => {
                  emptyPartnerScores[judge.id][candidate.id][criterion.id] = null;
                });
              }
            });
          });
          setPartnerScores(emptyPartnerScores);
        }

        // Mark as initialized to prevent re-fetching
        hasInitialized.current = true;
        setLoading(false);
      } catch (error) {
        console.error('Error fetching data:', error);
        setLoading(false);
      }
    };

    setLoading(true);
    fetchData();
  }, []); // Empty dependency - only run on mount

  // WebSocket handler for real-time score updates
  const handleScoreUpdate = useCallback((data) => {
    // Update single score from WebSocket event
    if (data.judge_id && data.candidate_id && data.criteria_id !== undefined) {
      setScores(prevScores => {
        const newScores = { ...prevScores };
        if (newScores[data.judge_id] && newScores[data.judge_id][data.candidate_id]) {
          newScores[data.judge_id][data.candidate_id][data.criteria_id] = data.points;
        }
        return newScores;
      });
    }
  }, []);

  // Get eventId from continuingEvent in localStorage or prop
  const eventId = useMemo(() => {
    if (continuingEvent) return continuingEvent.id;

    const continuingEventStr = localStorage.getItem('continuingEvent');
    if (continuingEventStr) {
      try {
        const continuingEvent = JSON.parse(continuingEventStr);
        return continuingEvent.id;
      } catch (e) {
        console.error('Error parsing continuingEvent:', e);
      }
    }
    return 1; // Fallback to 1
  }, [continuingEvent]);

  // Fetch scores when judges/categories/candidates change
  useEffect(() => {
    if (!hasInitialized.current || judges.length === 0 || categories.length === 0) {
      return;
    }

    const fetchScores = async () => {
      try {
        const apiBase = getApiBase();
        const response = await fetch(`${apiBase}/api/points?event_id=${eventId}`);
        if (response.ok) {
          const pointsData = await response.json();

          // Transform points data into scores structure
          const newScores = {};
          const newPartnerScores = {};

          judges.forEach(judge => {
            newScores[judge.id] = {};
            newPartnerScores[judge.id] = {};

            activeCandidates.forEach(candidate => {
              newScores[judge.id][candidate.id] = {};
              if (candidate.participant_type === 'duo' && candidate.partnership?.partner_name) {
                newPartnerScores[judge.id][candidate.id] = {};
              }

              categories.forEach(criterion => {
                const point = pointsData.find(p =>
                  p.judge_id === judge.id &&
                  p.candidate_id === candidate.id &&
                  p.criteria_id === criterion.id
                );

                newScores[judge.id][candidate.id][criterion.id] = point?.points || null;
              });
            });
          });

          setScores(newScores);
          setPartnerScores(newPartnerScores);
        }
      } catch (error) {
        console.error('Error fetching scores:', error);
      }
    };

    fetchScores();
  }, [judges, categories, activeCandidates]);

  // Setup WebSocket for real-time score updates (separate effect for stability)
  useEffect(() => {
    setIsLive(true);

    const echo = initializeEcho();
    if (echo) {
      const channelName = `scores.${eventId}`;
      console.log('📡 Attempting to connect to channel:', channelName);
      const channel = echo.channel(channelName);

      channel.subscribed(() => {
        console.log('✅ Successfully subscribed to channel:', channelName);
      });

      channel.error((error) => {
        console.error('❌ Channel subscription error:', error);
      });

      channel.listen('.ScoreUpdated', (data) => {
        handleScoreUpdate(data);
      });

      // Cleanup on unmount
      return () => {
        echo.leave(channelName);
        setIsLive(false);
      };
    }

    // Cleanup on unmount
    return () => {
      setIsLive(false);
    };
  }, [eventId, handleScoreUpdate]);

  if (loading) {
    return (
      <div className="flex items-center justify-center py-20">
        <div className="text-center">
          <div className="w-8 h-8 border-2 border-gray-300 border-t-blue-500 rounded-full animate-spin mx-auto mb-4"></div>
          <p className="text-sm text-gray-600">Loading scores...</p>
        </div>
      </div>
    );
  }
  if (!judges.length) return <EmptyState />;

  // Filter candidates
  const femaleCandidates = activeCandidates.filter(c => c.gender && c.gender.toLowerCase() === 'female');
  const maleCandidates = activeCandidates.filter(c => c.gender && c.gender.toLowerCase() === 'male');

  return (
    <div className="font-sans antialiased min-h-screen bg-gray-50 pb-20">
      {/* Round Header */}
      {activeRound && (
        <RoundHeader
          roundName={activeRound.name}
          eventId={eventId}
          // Control Props
          isVotingActive={isVotingActive}
          eventSequence={eventSequence}
          currentSequenceIndex={currentSequenceIndex}
          onStartStop={onStartStop}
          onNext={onNext}
          onOpenEventDetails={onOpenEventDetails}
        />
      )}

      {/* Main Content */}
      <div className="max-w-[1400px] mx-auto px-6 py-8">
        {femaleCandidates.length > 0 && (
          <ScoreTable
            title="Female Candidates"
            candidates={femaleCandidates}
            judges={judges}
            scores={scores}
            categories={categories}
            activeRound={activeRound}
            scoresHidden={scoresHidden}
            setScoresHidden={setScoresHidden}
            hasDuoParticipants={hasDuoParticipants}
            colorTheme="pink"
            candidateColors={candidateColors}
            getGroupColor={getGroupColor}
            getColumnColor={getColumnColor}
          />
        )}

        {maleCandidates.length > 0 && (
          <ScoreTable
            title="Male Candidates"
            candidates={maleCandidates}
            judges={judges}
            scores={scores}
            categories={categories}
            activeRound={activeRound}
            scoresHidden={scoresHidden}
            setScoresHidden={setScoresHidden}
            hasDuoParticipants={hasDuoParticipants}
            colorTheme="blue"
            candidateColors={candidateColors}
            getGroupColor={getGroupColor}
            getColumnColor={getColumnColor}
          />
        )}
      </div>
    </div>
  );
}

// backend/resources/js/components/admin/tabs/JudgesScoringTab.vue
<template>
  <div class="font-sans antialiased min-h-screen bg-white pb-20">
    <!-- Empty State -->
    <div v-if="!judges.length && !loading" class="text-center py-20">
      <span class="material-icons text-gray-300 mb-4" style="font-size: 64px">people</span>
      <p class="text-gray-500">No judges configured yet</p>
    </div>

    <!-- Main Content -->
    <template v-else-if="judges.length">
      <!-- Round Header -->
      <div class="bg-white border-b border-gray-200 px-6 py-3">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-xs text-gray-400 uppercase tracking-widest mb-1">Currently Scoring</p>
            <h2 class="text-xl font-bold text-gray-900 uppercase tracking-wide">
              {{ activeRound?.name || 'No Active Round' }}
            </h2>
          </div>
          <div class="flex items-center gap-2">
            <span class="flex items-center gap-1 text-xs text-green-600">
              <span class="w-2 h-2 bg-green-500 rounded-full animate-pulse"></span>
              Live
            </span>
          </div>
        </div>
      </div>

      <!-- Score Tables - Full Width -->
      <div class="w-full">
        <!-- Female Candidates -->
        <div v-if="femaleCandidates.length > 0">
          <div class="flex items-center justify-between px-6 py-3 bg-pink-50 border-b border-pink-200">
            <h3 class="text-sm font-semibold uppercase tracking-wide text-pink-600">Female Candidates</h3>
            <button
              @click="scoresHidden = !scoresHidden"
              class="flex items-center gap-1.5 px-3 py-1.5 rounded text-xs font-bold uppercase tracking-widest transition-all"
              :class="scoresHidden ? 'bg-slate-800 text-white' : 'bg-white text-slate-600 border border-slate-300'"
            >
              <span class="material-icons" style="font-size: 14px">{{ scoresHidden ? 'visibility_off' : 'visibility' }}</span>
              {{ scoresHidden ? 'Hidden' : 'Hide' }}
            </button>
          </div>
          
          <div class="bg-white overflow-x-auto">
            <table class="w-full border-collapse table-fixed">
              <colgroup>
                <col style="width: 30%">
                <col v-for="judge in judges" :key="'col-f-'+judge.id" :style="{ width: (60 / judges.length) + '%' }">
                <col style="width: 10%">
              </colgroup>
              <thead>
                <tr class="bg-gray-50 border-b border-gray-300">
                  <th class="py-3 px-6 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider border-r border-gray-200">Candidate</th>
                  <th v-for="judge in judges" :key="judge.id" class="py-3 px-4 text-center text-xs font-semibold text-gray-600 uppercase tracking-wider border-r border-gray-200">
                    Judge {{ judge.chair_number || judge.id }}
                  </th>
                  <th class="py-3 px-4 text-center text-xs font-semibold text-gray-600 uppercase tracking-wider">Total</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="candidate in femaleCandidates" :key="candidate.id" class="border-b border-gray-100 hover:bg-gray-50/50">
                  <td class="py-3 px-6 border-r border-gray-200">
                    <span class="font-semibold text-gray-900 text-sm uppercase">
                      {{ candidate.number }} - {{ candidate.name }}
                    </span>
                  </td>
                  <td v-for="judge in judges" :key="judge.id" class="py-3 px-4 text-center border-r border-gray-200">
                    <span :class="['font-mono text-sm', scoresHidden ? 'blur-md' : '']">
                      {{ getJudgeTotal(judge.id, candidate.id) || '-' }}
                    </span>
                  </td>
                  <td class="py-3 px-4 text-center">
                    <span :class="['font-mono text-sm font-bold text-blue-600', scoresHidden ? 'blur-md' : '']">
                      {{ getCandidateTotal(candidate.id) || '-' }}
                    </span>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <!-- Male Candidates -->
        <div v-if="maleCandidates.length > 0">
          <div class="flex items-center justify-between px-6 py-3 bg-blue-50 border-b border-blue-200">
            <h3 class="text-sm font-semibold uppercase tracking-wide text-blue-600">Male Candidates</h3>
          </div>
          
          <div class="bg-white overflow-x-auto">
            <table class="w-full border-collapse table-fixed">
              <colgroup>
                <col style="width: 30%">
                <col v-for="judge in judges" :key="'col-m-'+judge.id" :style="{ width: (60 / judges.length) + '%' }">
                <col style="width: 10%">
              </colgroup>
              <thead>
                <tr class="bg-gray-50 border-b border-gray-300">
                  <th class="py-3 px-6 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider border-r border-gray-200">Candidate</th>
                  <th v-for="judge in judges" :key="judge.id" class="py-3 px-4 text-center text-xs font-semibold text-gray-600 uppercase tracking-wider border-r border-gray-200">
                    Judge {{ judge.chair_number || judge.id }}
                  </th>
                  <th class="py-3 px-4 text-center text-xs font-semibold text-gray-600 uppercase tracking-wider">Total</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="candidate in maleCandidates" :key="candidate.id" class="border-b border-gray-100 hover:bg-gray-50/50">
                  <td class="py-3 px-6 border-r border-gray-200">
                    <span class="font-semibold text-gray-900 text-sm uppercase">
                      {{ candidate.number }} - {{ candidate.name }}
                    </span>
                  </td>
                  <td v-for="judge in judges" :key="judge.id" class="py-3 px-4 text-center border-r border-gray-200">
                    <span :class="['font-mono text-sm', scoresHidden ? 'blur-md' : '']">
                      {{ getJudgeTotal(judge.id, candidate.id) || '-' }}
                    </span>
                  </td>
                  <td class="py-3 px-4 text-center">
                    <span :class="['font-mono text-sm font-bold text-blue-600', scoresHidden ? 'blur-md' : '']">
                      {{ getCandidateTotal(candidate.id) || '-' }}
                    </span>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </template>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted, watch } from 'vue';
import { showError } from '../../../utils/alerts';

const props = defineProps({
  eventId: [String, Number],
  judges: Array,
  rounds: Array,
  candidates: Array,
  criteria: Array
});

const loading = ref(true);
const scoresHidden = ref(false);
const scores = ref({});
const activeRound = ref(null);
const isLive = ref(false);

// Pending updates buffer for batching WebSocket updates
let pendingUpdates = [];
let updateTimeout = null;

const femaleCandidates = computed(() => 
  (props.candidates || []).filter(c => c.gender?.toLowerCase() === 'female')
);

const maleCandidates = computed(() => 
  (props.candidates || []).filter(c => c.gender?.toLowerCase() === 'male')
);

const getJudgeTotal = (judgeId, candidateId) => {
  if (!scores.value[judgeId]?.[candidateId]) return null;
  const judgeScores = Object.values(scores.value[judgeId][candidateId]);
  const total = judgeScores.reduce((sum, score) => sum + (score || 0), 0);
  return total > 0 ? total.toFixed(2) : null;
};

const getCandidateTotal = (candidateId) => {
  let total = 0;
  props.judges?.forEach(judge => {
    if (scores.value[judge.id]?.[candidateId]) {
      Object.values(scores.value[judge.id][candidateId]).forEach(score => {
        total += score || 0;
      });
    }
  });
  return total > 0 ? total.toFixed(2) : null;
};

// Flush all pending updates in a single state update
const flushPendingUpdates = () => {
  if (pendingUpdates.length === 0) return;
  
  const updates = [...pendingUpdates];
  pendingUpdates = [];
  
  const newScores = { ...scores.value };
  updates.forEach(({ judgeId, batchScores }) => {
    if (!newScores[judgeId]) return;
    batchScores.forEach(score => {
      if (newScores[judgeId][score.candidate_id]) {
        newScores[judgeId][score.candidate_id][score.criteria_id] = score.points;
      }
    });
  });
  scores.value = newScores;
};

// Handle WebSocket score updates
const handleScoreUpdate = (data) => {
  // Handle batch updates from judges
  if (data.is_batch && data.batch_scores) {
    pendingUpdates.push({
      judgeId: data.judge_id,
      batchScores: data.batch_scores
    });
    
    // Debounce: wait 50ms for more updates before rendering
    if (updateTimeout) clearTimeout(updateTimeout);
    updateTimeout = setTimeout(flushPendingUpdates, 50);
    return;
  }

  // Handle single score update (backward compatibility)
  if (data.judge_id && data.candidate_id && data.criteria_id !== undefined) {
    pendingUpdates.push({
      judgeId: data.judge_id,
      batchScores: [{ candidate_id: data.candidate_id, criteria_id: data.criteria_id, points: data.points }]
    });
    
    if (updateTimeout) clearTimeout(updateTimeout);
    updateTimeout = setTimeout(flushPendingUpdates, 50);
  }
};

const loadScores = async () => {
  if (!props.eventId) return;
  
  try {
    const response = await fetch(`/api/points?event_id=${props.eventId}`);
    const pointsData = await response.json();
    
    const newScores = {};
    props.judges?.forEach(judge => {
      newScores[judge.id] = {};
      props.candidates?.forEach(candidate => {
        newScores[judge.id][candidate.id] = {};
        props.criteria?.forEach(criterion => {
          newScores[judge.id][candidate.id][criterion.id] = null;
        });
      });
    });
    
    pointsData.forEach(point => {
      if (newScores[point.judge_id]?.[point.candidate_id]) {
        newScores[point.judge_id][point.candidate_id][point.criteria_id] = point.points;
      }
    });
    
    scores.value = newScores;
  } catch (error) {
    showError('Failed to load scores');
  }
};

const loadVotingState = async () => {
  if (!props.eventId) return;
  
  try {
    const response = await fetch(`/api/voting/state?event_id=${props.eventId}`);
    const data = await response.json();
    activeRound.value = data.active_round;
  } catch (error) {
    showError('Failed to load voting state');
  }
};

// Setup WebSocket connection
const setupWebSocket = () => {
  if (!props.eventId || !window.Echo) return;
  
  const channelName = `scores.${props.eventId}`;
  console.log('📡 JudgesScoringTab: Connecting to channel:', channelName);
  
  const channel = window.Echo.channel(channelName);
  
  channel.subscribed(() => {
    console.log('✅ JudgesScoringTab: Successfully subscribed to channel:', channelName);
    isLive.value = true;
  });
  
  channel.listen('.ScoreUpdated', (data) => {
    console.log('📥 Score update received:', data);
    handleScoreUpdate(data);
  });
  
  return channelName;
};

let currentChannel = null;

onMounted(async () => {
  await loadVotingState();
  await loadScores();
  loading.value = false;
  
  // Setup WebSocket after data is loaded
  currentChannel = setupWebSocket();
});

onUnmounted(() => {
  // Cleanup WebSocket
  if (currentChannel && window.Echo) {
    window.Echo.leave(currentChannel);
    console.log('🔌 Left channel:', currentChannel);
  }
  if (updateTimeout) {
    clearTimeout(updateTimeout);
  }
  isLive.value = false;
});

// Re-setup WebSocket if eventId changes
watch(() => props.eventId, (newEventId, oldEventId) => {
  if (newEventId !== oldEventId) {
    if (currentChannel && window.Echo) {
      window.Echo.leave(currentChannel);
    }
    currentChannel = setupWebSocket();
  }
});
</script>
